### ISSUE TITLE
mogelijk aanpassen volgorde van de lijsten

### ISSUE THREAD

**Issue by alfamongrel** [Activisme-be/activisme.be#38]
bij de backend van de lijsten die ze kunnen aanpassen een mogelijkheid programmeren voor de volgorde van de petities enz

**Comment by Tjoosten** [comment]
- [ ] Toevoegen timestamp afloop acties. 
- [ ] Orderen op afloop datum.

**Comment by alfamongrel** [comment]
en ook manueel kunnen naar de top plaatsen

**Comment by Tjoosten** [comment]
Manueel word moeilijk. Aangezien je dan met een drag en drop systeem moet worden gebouwd. Daar heb ik momenteel niet echt een oplossing voor. Dus ik stel voor dat we na de timestamp implementatie het ticket sluiten.

En op een later tijdstip hiervoor een nieuw ticket aanmaken.
