### ISSUE TITLE
aanpassing voor de front-end van de index

### ISSUE THREAD

**Issue by alfamongrel** [Activisme-be/activisme.be#47]
wanneer de lijst leeg is moet er duidelijk leesbaar zijn die leeg is !
met witte letters 
vb: 
Er zijn nu geen mail acties 
enz.....

**Comment by Tjoosten** [comment]
Bedoel je niet de front-end want de backend geeft een alert message weer.

**Comment by alfamongrel** [comment]
ja dat het zichtbaar is in de front end duidelijk witte tekst

**Comment by Tjoosten** [comment]
@TeppersBen Fout lokaal gevonden. Ik stel voor dat ik die afhandel aangezien de fout is de back-end structuur zit.
