### ISSUE TITLE
Mail actie wil niet plaatsen 

### ISSUE THREAD

**Issue by alfamongrel** [Activisme-be/activisme.be#48]
De mail actie tegen kernwapens maakt niet aan 
https://nonukes.be/nederlands/actie/mail-michel/

FOUT : 
<details>an uncaught Exception was encountered

Type: Illuminate\Database\QueryException

Message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'https://nonukes.be/nederlands/actie/mail-michel/' for key 'links_link_uindex' (SQL: insert into `links` (`name`, `link`, `author_id`, `type_id`, `updated_at`, `created_at`) values (Mail tegen kernwapens, https://nonukes.be/nederlands/actie/mail-michel/, 6, 2, 2017-04-24 18:23:04, 2017-04-24 18:23:04))

Filename: /customers/6/4/2/activisme.be/httpd.www/vendor/illuminate/database/Connection.php

Line Number: 647

Backtrace:

File: /customers/6/4/2/activisme.be/httpd.www/vendor/illuminate/database/Connection.php
Line: 607
Function: runQueryCallback

File: /customers/6/4/2/activisme.be/httpd.www/vendor/illuminate/database/Connection.php
Line: 450
Function: run

File: /customers/6/4/2/activisme.be/httpd.www/vendor/illuminate/database/Connection.php
Line: 404
Function: statement

File: /customers/6/4/2/activisme.be/httpd.www/vendor/illuminate/database/Query/Processors/Processor.php
Line: 32
Function: insert

File: /customers/6/4/2/activisme.be/httpd.www/vendor/illuminate/database/Query/Builder.php
Line: 2196
Function: processInsertGetId

File: /customers/6/4/2/activisme.be/httpd.www/vendor/illuminate/database/Eloquent/Builder.php
Line: 1319
Function: insertGetId

File: /customers/6/4/2/activisme.be/httpd.www/vendor/illuminate/database/Eloquent/Model.php
Line: 674
Function: __call

File: /customers/6/4/2/activisme.be/httpd.www/vendor/illuminate/database/Eloquent/Model.php
Line: 639
Function: insertAndSetId

File: /customers/6/4/2/activisme.be/httpd.www/vendor/illuminate/database/Eloquent/Model.php
Line: 508
Function: performInsert

File: /customers/6/4/2/activisme.be/httpd.www/vendor/illuminate/database/Eloquent/Builder.php
Line: 817
Function: save

File: /customers/6/4/2/activisme.be/httpd.www/vendor/illuminate/database/Eloquent/Model.php
Line: 1316
Function: create

File: /customers/6/4/2/activisme.be/httpd.www/vendor/illuminate/database/Eloquent/Model.php
Line: 1328
Function: __call

File: /customers/6/4/2/activisme.be/httpd.www/application/controllers/Links.php
Line: 63
Function: __callStatic

File: /customers/6/4/2/activisme.be/httpd.www/index.php
Line: 315
Function: require_once</details>

**Comment by Tjoosten** [comment]
Waiting for Fix confirmation @alfamongrel
