### ISSUE TITLE
1 complete enkele pagina

### ISSUE THREAD

**Issue by alfamongrel** [Activisme-be/activisme.be#54]
Is het mogelijk om 1 enkele complete pagina te maken van uit de crowdfund pagina,
waar de header en de footer 1 geheel zijn,
waar we makkelijk en vlug andere enkele pagina`s kunnen maken voor evenementen en crowfunds

**Comment by TeppersBen** [comment]
@alfamongrel Is het mogelijk om een ruimere omschrijving te geven van dit idee?

vb:
- Wil jij de header-image zelf kunnen aanpassen
- Is er nood aan manipulatie van kleuren (shadow colors)
- Specifieke veranderingen in opbouw van de pagina
- Leek-Friendly modification (makkelijk aanpasbaar voor mensen zonder HTML/CSS kennis)
- Documentatie (legt je uit hoe de pagina gemaakt wordt / zou moeten worden)
- ...

Alvast bedankt

**Comment by alfamongrel** [comment]
ja de image wil ik zelf kunnen importeren 
titel ook wil ik zelf 1 zetten of wegnemen 
kleuren aanpasbaar
bouw all gelijk 
liefst vriendelijk
ok dank je

**Comment by Tjoosten** [comment]
#56 Kan hierbij helpen.

**Comment by TeppersBen** [comment]
Komt in orde, ga eveneens SCSS proberen bij deze pagina

**Comment by Tjoosten** [comment]
SCSS is al embedded in het platform. Alle plain text css word overschreven door de task runnes

**Comment by TeppersBen** [comment]
👍

**Comment by alfamongrel** [comment]
Hoe ver staan we met die enkele pagina want ik heb een activisme growdfund pagina nodig redelijk dringend

**Comment by TeppersBen** [comment]
@alfamongrel Heb deze week nog één PE te gaan voor woensdag, voor de rest moet ik de deadline van c# programmatie projecten ook nog halen, Hoop dat ze mij donderdag 4u gerust laten op school en vrijdag 2u, dan is dat ten laatste Vrijdag 5 Mei af om 12.30.

**Comment by TeppersBen** [comment]
@Tjoosten is het mogelijk om mij te laten weten waar ik de HTML file mag uploaden voor @alfamongrel en waar de CSS van deze pagina moet staan?

alvast bedankt

**Comment by Tjoosten** [comment]
Goh, goeie vraag. Zou jij het zien zitten om even een repo aan te maken. Tot ik de tijd heb om het eens te bekijken?

**Comment by TeppersBen** [comment]
👍 pagina vordert goed, moet de documentatie nog eens goed doornemen zodat het heel erg duidelijk is.

**Comment by TeppersBen** [comment]
@Tjoosten @alfamongrel tijdens het werken aan de pagina kreeg ik het idee waar ik jullie mening over wil hebben.

Wat als ik een applicatie ontwikkel die crowdfund pagina's kan genereren, enigste wat van de persoon gevraagd wordt is om een x-aantal velden in te vullen.

applicatie zorgt voor:
- een flexibele werking met HTML/PHP en CSS/SCSS;
- een gebruiksvriendelijke werking;
- een export (HTML/CSS) versie, (testen op eigen machine)
- een export (PHP/SCSS) versie, (productief voor server)

Dit idee zou te realiseren zijn door een repo aan te maken "Crowdfund Generator" waar het Java project in staat. Hierdoor kunnen jullie de vooruitgang van de applicatie volgen 24/7.
Indien er geen tickets zijn voor mij op deze repo "Activisme.be" kan ik aan het project werken.

Indien er groen licht is om dit te maken laat je het mij maar weten.

**Comment by alfamongrel** [comment]
dit zou niet enkel voor crowdfundpagina moeten zijn dit voor elke enkele pagina we willen maken vd acties en uitleg enz

**Comment by Tjoosten** [comment]
@TeppersBen @alfamongrel dan ben je eigenlijk een backend systeem aan het nabootsten he, Aangezien een backend-systeem het zelfde doet

**Comment by Tjoosten** [comment]
Ticket niet meer relevant en inactief. Ik stel voor dat we deze sluiten. Indien nog mag deze heropend worden
