### ISSUE TITLE
Caravan crowdfund logo sponsors

### ISSUE THREAD

**Issue by alfamongrel** [Activisme-be/activisme.be#59]
Mogelijk die nog eens te herbekijken die vallen nu wel heel groot uit ?
wanneer je op smartphone kijkt vallen er buiten de background

**Comment by Tjoosten** [comment]
9/10 CSS related

**Comment by alfamongrel** [comment]
![18175826_1189467771175333_912653139_o](https://cloud.githubusercontent.com/assets/23736363/25527600/bed0d440-2c19-11e7-982b-e8defcc2e01a.png)
op scss werkt het niet maar op css wel blijkbaar

**Comment by Tjoosten** [comment]
Dat zou vrij zijn aangezien de scss exact het helfde is dat de css

**Comment by Tjoosten** [comment]
@TeppersBen heb jij zicht op dit ticket? Zoja kun je me een update geven?

**Comment by Tjoosten** [comment]
Unassigned @TeppersBen. Ik ga het laten nakijken door senior engineer op het werk
