### ISSUE TITLE
Index aanpassing

### ISSUE THREAD

**Issue by alfamongrel** [Activisme-be/activisme.be#61]
gelieve boven over ons de bijgevoegde tekt bij te voegen 

dan er onder "over ons" word - kort overzicht

en boven de nieuwe tekst "over ons"

gelieve dit wel al op zelfste background dus blad te doen !
[Activisme.docx](https://github.com/Activisme-be/activisme.be/files/974538/Activisme.docx)

ik wil duidelijk eerst het gezien hebben voor de release er van

REF: #60

**Comment by Tjoosten** [comment]
**EDIT:** Titel aangepast wegens label indicatie

**Comment by Tjoosten** [comment]
Over ons de tekst moet eronder. (Titel)

En boven de punten moet de titel kort overzicht

**Comment by TeppersBen** [comment]
![prototype1](https://cloud.githubusercontent.com/assets/24385407/25798328/01a80dfa-33e1-11e7-80b1-c04e14669ddf.PNG)

**Comment by TeppersBen** [comment]
![prototype2](https://cloud.githubusercontent.com/assets/24385407/25799279/b5253ea4-33e4-11e7-9157-fe1d10d3d16b.PNG)
Op aanvraag van de organisator @alfamongrel ziet het er als volgt uit.

**Comment by Tjoosten** [comment]
Ik heb het ticket heropend wachten op validatie van @alfamongrel

**Comment by alfamongrel** [comment]
Ben gelieve de 3 talen te voorzien !
nederlands op de site,
frans en engels in een document zo dat Tim dit kan in de backlog pompen 
dank U

**Comment by alfamongrel** [comment]
De index pagina komt miet overeen met de foto hier door Ben gepost !
gelieve dringend de tekst opmaak en lettertype gelijk foto van 8 mei te maken aub
