### ISSUE TITLE
Herindelen paginas

### ISSUE THREAD

**Issue by TeppersBen** [Activisme-be/activisme.be#68]
ipv importaties moet alles in één document staan

**Comment by Tjoosten** [comment]
Kan je iets specifieker zijn. Want mij persoonlijk lijkt het vrij vaag momenteel.

**Comment by Tjoosten** [comment]
Als het omtrent de `@includes` gaat. Zou ik graag een goede argumentering hebben aangezien deze worden gebruikt voor weerkerende code. 

De includes zijn erin gestoken omdat het perfect kan met de back-end en code reduplicatie te vermijden.

**Comment by TeppersBen** [comment]
Zodra Tom zijn computer opnieuw is geïnstalleerd, zal hier meer uitleg over komen. Heb dit in opdracht gedaan van hem.

**Comment by Tjoosten** [comment]
Alright!
